/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package MortgageCalculator;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ItemEvent;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author jason pearl
 */

public class MortCalcFrame extends javax.swing.JFrame {

    /**
     * Creates new form MortCalcFrame
     */
    public MortCalcFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mortDataLabel = new javax.swing.JLabel();
        clientName = new javax.swing.JTextField();
        clientNameLabel = new javax.swing.JLabel();
        annualInterestLabel = new javax.swing.JLabel();
        annualInterestRate = new javax.swing.JTextField();
        loanYearsLabel = new javax.swing.JLabel();
        loanYears = new javax.swing.JTextField();
        loanAmountLabel = new javax.swing.JLabel();
        loanAmount = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();
        extrasLabel = new javax.swing.JLabel();
        hoaFee = new javax.swing.JTextField();
        otherFee = new javax.swing.JTextField();
        hoaCheckBox = new javax.swing.JCheckBox();
        otherCheckBox = new javax.swing.JCheckBox();
        errorLabel = new javax.swing.JLabel();
        startMonthLabel = new javax.swing.JLabel();
        month = new javax.swing.JTextField();
        startYearLabel = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        TabbedPane = new javax.swing.JTabbedPane();
        summaryPane = new javax.swing.JScrollPane();
        summaryOutput = new javax.swing.JTextArea();
        graphPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        dummyClient = new javax.swing.JMenuItem();
        saveClient = new javax.swing.JMenuItem();
        print = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        clear = new javax.swing.JMenuItem();
        clientMenu = new javax.swing.JMenu();
        helpMenu = new javax.swing.JMenu();
        help = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mortgage Calculator");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        mortDataLabel.setForeground(new java.awt.Color(0, 59, 255));
        mortDataLabel.setText("Enter Mortgage Data");

        clientName.setForeground(new java.awt.Color(0, 59, 255));

        clientNameLabel.setText("Client Name:");
        clientNameLabel.setToolTipText("Enter your clients name.");

        annualInterestLabel.setText("Annual interest rate:");
        annualInterestLabel.setToolTipText("Enter the Interest Rate(ex. 8.5)");

        annualInterestRate.setForeground(new java.awt.Color(0, 59, 255));
        annualInterestRate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        loanYearsLabel.setText("Loan years total:");
        loanYearsLabel.setToolTipText("Enter the length of loan in years.(ex. 40)");

        loanYears.setForeground(new java.awt.Color(0, 59, 255));
        loanYears.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        loanAmountLabel.setText("Loan Amount:");
        loanAmountLabel.setToolTipText("Enter the loan amount.(ex. 120000)");

        loanAmount.setForeground(new java.awt.Color(0, 59, 255));
        loanAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        calculateButton.setText("Calculate Mortgage Data");
        calculateButton.setToolTipText("Click to run the Calculations!");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        extrasLabel.setText("Extra Additions");
        extrasLabel.setToolTipText("Extra add ons to the monthly mortgage");

        hoaFee.setForeground(new java.awt.Color(0, 59, 255));
        hoaFee.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hoaFee.setText("0");
        hoaFee.setEnabled(false);

        otherFee.setForeground(new java.awt.Color(0, 59, 255));
        otherFee.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        otherFee.setText("0");
        otherFee.setEnabled(false);

        hoaCheckBox.setText("HOA monthly fee:");
        hoaCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                hoaCheckBoxItemStateChanged(evt);
            }
        });
        hoaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoaCheckBoxActionPerformed(evt);
            }
        });

        otherCheckBox.setText("Other monthly fee:");
        otherCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                otherCheckBoxItemStateChanged(evt);
            }
        });
        otherCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherCheckBoxActionPerformed(evt);
            }
        });

        errorLabel.setForeground(new java.awt.Color(255, 0, 0));

        startMonthLabel.setText("Start Month(ex. mm):");

        month.setForeground(new java.awt.Color(0, 59, 255));
        month.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        startYearLabel.setText("Start Year(ex. yyyy):");

        year.setForeground(new java.awt.Color(0, 59, 255));
        year.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calculateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(annualInterestLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(annualInterestRate, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(mortDataLabel)
                                        .addGap(66, 66, 66))
                                    .addComponent(clientName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(71, 71, 71)
                                            .addComponent(extrasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(clientNameLabel)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(loanAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(loanYearsLabel))
                                            .addGap(28, 28, 28)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(loanAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(loanYears, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(hoaCheckBox)
                                            .addComponent(otherCheckBox)
                                            .addComponent(startYearLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(year)
                                            .addComponent(month, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(otherFee, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(hoaFee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(errorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(startMonthLabel)
                        .addContainerGap())))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {clientName, loanAmount});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(mortDataLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annualInterestLabel)
                    .addComponent(annualInterestRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loanYearsLabel)
                    .addComponent(loanYears, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loanAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loanAmountLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startMonthLabel)
                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startYearLabel)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(extrasLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoaCheckBox)
                    .addComponent(hoaFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(otherFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(otherCheckBox))
                .addGap(30, 30, 30)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(calculateButton)
                .addGap(31, 31, 31))
        );

        summaryOutput.setColumns(20);
        summaryOutput.setRows(5);
        summaryPane.setViewportView(summaryOutput);

        TabbedPane.addTab("Summary", summaryPane);

        graphPanel.setBackground(new java.awt.Color(254, 254, 254));

        javax.swing.GroupLayout graphPanelLayout = new javax.swing.GroupLayout(graphPanel);
        graphPanel.setLayout(graphPanelLayout);
        graphPanelLayout.setHorizontalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 831, Short.MAX_VALUE)
        );
        graphPanelLayout.setVerticalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );

        TabbedPane.addTab("Graph", graphPanel);

        fileMenu.setText("File");

        dummyClient.setText("Dummy Client");
        dummyClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dummyClientActionPerformed(evt);
            }
        });
        fileMenu.add(dummyClient);

        saveClient.setText("Save Client");
        saveClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveClientActionPerformed(evt);
            }
        });
        fileMenu.add(saveClient);

        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        fileMenu.add(print);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        fileMenu.add(exit);

        menuBar.add(fileMenu);

        editMenu.setText("Edit");

        clear.setText("Clear Entries");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        editMenu.add(clear);

        menuBar.add(editMenu);

        clientMenu.setText("Clients");
        menuBar.add(clientMenu);

        helpMenu.setText("Help");

        help.setText("Get Help");
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });
        helpMenu.add(help);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
       System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void hoaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoaCheckBoxActionPerformed
        hoaFee.setEnabled(true);
    }//GEN-LAST:event_hoaCheckBoxActionPerformed

    private void otherCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherCheckBoxActionPerformed
        otherFee.setEnabled(true);
    }//GEN-LAST:event_otherCheckBoxActionPerformed

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
       //calculate the mortgage term and display the fields 
        
    try {  MortgageClient client = new MortgageClient(clientName.getText(), Double.parseDouble(annualInterestRate.getText()), + 
               Integer.parseInt(loanYears.getText()), Double.parseDouble(loanAmount.getText()), +
               Integer.parseInt(month.getText()), Integer.parseInt(year.getText()), Double.parseDouble(hoaFee.getText()), +
               Double.parseDouble(otherFee.getText())); 
    
       summaryOutput.setText(client.calulateMortgage());
       summaryOutput.moveCaretPosition(1);
   
    }catch (NumberFormatException e){
        errorLabel.setText("Fill in all of the boxes to continue.");
    
    } 
    Graph g = new Graph();
    graphPanel.add(g);
    
   
        
        
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void dummyClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dummyClientActionPerformed
        
      MortgageClient dummy = new MortgageClient();
        
      clientName.setText("Some Client");
      annualInterestRate.setText("3.5");
      loanYears.setText("30");
      loanAmount.setText("100000");
      month.setText("7");
      year.setText("2012");
    }//GEN-LAST:event_dummyClientActionPerformed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        //help document that shows up on the summary pane
       
        summaryOutput.setText("\t\t\t\tHelp Document\n\n" +
                "\tThis Mortgage application will get your information and calculate the cost of a mortgage on a house. \nIt will also figure out how much is " +
                "going to principle and how much is going to interest. You can also add other " + "\nmonthly fees that you may have. " +
                "If you just want to test the application to see it work, you can use a dummy client. \nClick \"File > Dummy Client\" to fill in the fields for you." +
                "\n\n If you have any issues, contact me: \n\n Jason Pearl\njas2069297@maricopa.edu");
    }//GEN-LAST:event_helpActionPerformed

    private void hoaCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_hoaCheckBoxItemStateChanged
        if (evt.getStateChange() == ItemEvent.DESELECTED) {
            hoaFee.setEnabled(false);
            hoaFee.setText("0");
        }
            
    }//GEN-LAST:event_hoaCheckBoxItemStateChanged

    private void otherCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_otherCheckBoxItemStateChanged
        if (evt.getStateChange() == ItemEvent.DESELECTED) {
            otherFee.setEnabled(false);
            otherFee.setText("0");
        }
    }//GEN-LAST:event_otherCheckBoxItemStateChanged
//clear the contents of the text boxes
    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
         
        clientName.setText("");
      annualInterestRate.setText("");
      loanYears.setText("");
      loanAmount.setText("");
      month.setText("");
      year.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
       //print summay field
        
        try {
            summaryOutput.print();
        } catch (PrinterException ex) {
            Logger.getLogger(MortCalcFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_printActionPerformed

    private void saveClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveClientActionPerformed
         final javax.swing.JMenuItem savedClient;
        //creates a new client
        final MortgageClient client = new MortgageClient();
        
        client.createClient(new MortgageClient(clientName.getText(), Double.parseDouble(annualInterestRate.getText()), + 
               Integer.parseInt(loanYears.getText()), Double.parseDouble(loanAmount.getText()), +
               Integer.parseInt(month.getText()), Integer.parseInt(year.getText()), Double.parseDouble(hoaFee.getText()), +
               Double.parseDouble(otherFee.getText())));
        //saves the client to a new menu item
        savedClient = new javax.swing.JMenuItem();
        clientMenu.add(savedClient);
        savedClient.setText(clientName.getText());
        // create listener for the menu item
        savedClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadClientActionPerformed(evt);
            }
            //when clicking on a client name, get the name from the array and populate the text fields with the user data
            
             void loadClientActionPerformed(ActionEvent evt) {

                for (int i = 0; i < client.getActiveClientAccountCount(); i++) {
    		if (savedClient.getText().equals(client.clientAccount[i].getName())) {
    		
    		clientName.setText(client.clientAccount[i].getName());
                annualInterestRate.setText(String.valueOf(client.clientAccount[i].getAnnualInterestRate()));
                loanYears.setText(String.valueOf(client.clientAccount[i].getLoanYears()));
                loanAmount.setText(String.valueOf(client.clientAccount[i].getLoanAmount()));
                month.setText(String.valueOf(client.clientAccount[i].getStartMonth()));
                year.setText(String.valueOf(client.clientAccount[i].getStartYear()));
                hoaFee.setText(String.valueOf(client.clientAccount[i].getHoaFee()));
                otherFee.setText(String.valueOf(client.clientAccount[i].getOtherFee()));
    		}
            } }
       
        });
       
    }//GEN-LAST:event_saveClientActionPerformed


           

           
                
    	
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MortCalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MortCalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MortCalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MortCalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MortCalcFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JLabel annualInterestLabel;
    private javax.swing.JTextField annualInterestRate;
    private javax.swing.JButton calculateButton;
    private javax.swing.JMenuItem clear;
    private javax.swing.JMenu clientMenu;
    private javax.swing.JTextField clientName;
    private javax.swing.JLabel clientNameLabel;
    private javax.swing.JMenuItem dummyClient;
    private javax.swing.JMenu editMenu;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JMenuItem exit;
    private javax.swing.JLabel extrasLabel;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPanel graphPanel;
    private javax.swing.JMenuItem help;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JCheckBox hoaCheckBox;
    private javax.swing.JTextField hoaFee;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField loanAmount;
    private javax.swing.JLabel loanAmountLabel;
    private javax.swing.JTextField loanYears;
    private javax.swing.JLabel loanYearsLabel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextField month;
    private javax.swing.JLabel mortDataLabel;
    private javax.swing.JCheckBox otherCheckBox;
    private javax.swing.JTextField otherFee;
    private javax.swing.JMenuItem print;
    private javax.swing.JMenuItem saveClient;
    private javax.swing.JLabel startMonthLabel;
    private javax.swing.JLabel startYearLabel;
    private javax.swing.JTextArea summaryOutput;
    private javax.swing.JScrollPane summaryPane;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables

}
